#Test Train Split

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from google.colab import drive
drive.mount("/content/drive", force_remount=True)
df = pd.read_csv("/content/drive/My Drive/Rtfp/processed_cleveland.csv")
X = df.drop("target", axis=1)
y = df["target"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


Mounted at /content/drive


#Logistic Regression


In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import StratifiedKFold
import numpy as np

model = LogisticRegression(max_iter=1000)
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

accuracies = []

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y), 1):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    accuracies.append(acc)

    print(f"\nFold {fold}")
    print("Accuracy:", acc)
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))



Fold 1
Accuracy: 0.8524590163934426
Confusion Matrix:
 [[30  3]
 [ 6 22]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.91      0.87        33
           1       0.88      0.79      0.83        28

    accuracy                           0.85        61
   macro avg       0.86      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61


Fold 2
Accuracy: 0.819672131147541
Confusion Matrix:
 [[29  4]
 [ 7 21]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.88      0.84        33
           1       0.84      0.75      0.79        28

    accuracy                           0.82        61
   macro avg       0.82      0.81      0.82        61
weighted avg       0.82      0.82      0.82        61


Fold 3
Accuracy: 0.8524590163934426
Confusion Matrix:
 [[29  4]
 [ 5 23]]
Classification Report:
               precision    recall  f1-score   supp

In [6]:
print("\nAverage K-Fold Accuracy:", np.mean(accuracies))



Average K-Fold Accuracy: 0.8449180327868853


In [ ]:
import joblib
joblib.dump(model, '/content/drive/My Drive/Rtfp/models/logistic_model.pkl')


['/content/drive/My Drive/Rtfp/models/logistic_model.pkl']